# Site
name: Elias Arruda
description: Apenas mais um site
meta_description: Apenas mais um site
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'arrudaelias1@gmail.com'
google_analytics:
disqus:
sharethis:

# Authors
authors:
  john:
    name: elias
    display_name: Elias Arruda
    image: /assets/images/john.jpg
    email: arrudaelias1@gmail.com
    web: https://arrudaelias.github.io/
    twitter:
    description: Olá, eu sou  Elias.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: elias
  card: summary

facebook:
  app_id:
  publisher: arrudaelias.github.io
  admins:

social:
name: Arruda Elias
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
